spring.application.name=backend


# ==========================================
# CONFIGURACIÓN DE LA BASE DE DATOS POSTGRE
# ==========================================
# Puerto dinámico
server.port=${PORT:8080}

# Conexión a Base de Datos mediante Variables de Entorno
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pomodorowar}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false

# Clave JWT
jwt.secret=${JWT_SECRET:UG9tb2Rvcm9XYXJTZWNyZXRLZXlQYXJhRWxUb2tlbkJlYXJlckRlVHVURkcyMDI2}

## Recuperar contrasena
spring.mail.host=smtp.gmail.com
# Cambiamos del puerto 587 al 465
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME:tu-correo-local@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tu-password-local}

spring.mail.properties.mail.smtp.auth=true
# Apagamos STARTTLS y encendemos SSL puro
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.required=true