spring.application.name=backend


# ==========================================
# CONFIGURACIÓN DE LA BASE DE DATOS POSTGRE
# ==========================================
# Puerto dinámico
server.port=${PORT:8080}

# Conexión a Base de Datos mediante Variables de Entorno
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pomodorowar}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:admin}

# ==========================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.generate-ddl=true
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false

# Clave JWT
jwt.secret=${JWT_SECRET:UG9tb2Rvcm9XYXJTZWNyZXRLZXlQYXJhRWxUb2tlbkJlYXJlckRlVHVURkcyMDI2}

# ==========================================
# CONFIGURACIÓN DE CORREO API REST
# ==========================================
resend.api.key=${RESEND_API_KEY:NO_KEY}
resend.sender.email=${RESEND_SENDER_EMAIL:Fortaleza Pomodoro <onboarding@resend.dev>}

#Swagger
springdoc.api-docs.enabled=false